### ISSUE TITLE
Accounting for dependencies in cmake between IDL files included by the #include directive

### ISSUE THREAD

**Issue by i-and** [eclipse-cyclonedds/cyclonedds#697]
In the file https://github.com/eclipse-cyclonedds/cyclonedds/blob/master/src/idlc/cmake/IdlcGenerate.cmake the following is present:
```
    add_custom_command(
      OUTPUT   "${_source}" "${_header}"
      COMMAND  "${IDLC_DIR}/${IDLC}"
      ARGS     ${IDLC_ARGS} ${ABS_FIL}
      DEPENDS  "${ABS_FIL}" idlc
      COMMENT  "Running idlc on ${FIL}"
      VERBATIM)
```
As a result, recompilation does not take into account the modification dates of the included IDL files. The reassembly may not be complete. How to fix it?

**Comment by k0ekk0ek** [comment]
Hi @i-and. That's normally what the `DEPENDS` option is for. At least, that's what it says in the [documentation](https://cmake.org/cmake/help/latest/command/add_custom_command.html). So, it should work, but if it isn't then it might be we're not using it correctly there. I'll have quick look.

**Comment by k0ekk0ek** [comment]
@i-and, did some quick tests with the helloworld example. Both a simple `touch` and actually adding another member to the struct. In both cases, when running `cmake --build .` for the example, the IDL file was parsed again and the executable rebuilt. Maybe there's a specific case in which it doesn't though? Can you provide some more details?

**Comment by i-and** [comment]
Hi, @k0ekk0ek. To recreate this situation, you need to slightly modify the HelloWorld example as follows:
1. create new idl file for example `included.idl`
2. insert the string `#include "included.idl` in the HelloWorldData.idl file
3. add the `included.idl` file to the `idlc_generate()` macro
When changing the included.idl file, the generation for the HelloWorldData.idl is not performed.

The situation is corrected by using `IMPLICIT_DEPENDS C "${ABS_FIL}"` in the `add_custom_command()`.

But _"Note that the IMPLICIT_DEPENDS option is currently supported only for Makefile generators and will be ignored by other generators._"

**Comment by k0ekk0ek** [comment]
@i-and, reading this again I realize the actual problem. I'm not quite sure how to solve it yet though. We generate a custom command for each IDL file and group them by adding a custom target. We depend on CMake for that and include dependencies are not resolved at that point as that's done by the C compiler. I suppose I could add some simple scanning of `#include` directives and update the `DEPENDS` field of the custom commands accordingly, but that seems error prone. If I update a file by adding an include, that include will not be depended on as the commands are generated at configure time. I'll look into it. Thanks for reporting!

**Comment by i-and** [comment]
@k0ekk0ek, doesn't the `IMPLICIT_DEPENDS C "${ABS_FIL}` option in the `add_custom_command()` solve the problem?
``` cmake
 add_custom_command(
      OUTPUT   "${_source}" "${_header}"
      COMMAND  "${IDLC_DIR}/${IDLC}"
      ARGS     ${IDLC_ARGS} ${ABS_FIL}
      DEPENDS  "${ABS_FIL}" idlc
      COMMENT  "Running idlc on ${FIL}"
      IMPLICIT_DEPENDS C "${ABS_FIL}
      VERBATIM)
```
This option (`IMPLICIT_DEPENDS`) worked for me, but only for Makefile generators, as it is written in the `cmake`documentation.

**Comment by k0ekk0ek** [comment]
Didn't know about `IMPLICIT_DEPENDS`, but that is indeed the kind of behavior we are looking for. Since that only works for Makefile generators I'll have to look into it a bit further. If no alternatives to it exist I guess having it working for one type of generator is better than nothing :slightly_smiling_face:

**Comment by k0ekk0ek** [comment]
@i-and, I've played around with it a bit and the cleanest solution would be to add a custom target that scans for dependencies as a dependency for the `<target>_idlc_generate` target. The pre-generate target would output (`BYPRODUCTS`) a stamp file that serves as a dependency for the generate command executed with `add_custom_command`. The best way to scan the dependencies is to process the `#line` directives from the idl preprocessor (environment variables etc might play a role). The problem with this is that the Java-based compiler that's currently used does not allow the user to only preprocess files, as a matter of fact, there's no preprocessor in there at all. The compiler that's currently in the `xtypes` branch does allow the user to only preprocess.

The best short term solution is probably to add every input file to the `DEPENDS` of every `add_custom_command` so that all sources are regenerated if one is updated. I'd say that's good enough for the short term. Not as fancy as using `IMPLICIT_DEPENDS` or the separate target, but does work on all generators.

**Comment by k0ekk0ek** [comment]
Thanks for reporting @i-and! Fix is merged to master.
